version: '3.7'

services:
  main:
    container_name: main
    image: node
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
      - mongo
  postgres:
    container_name: postgres
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - webnet
    ports:
      - 27018:27017
networks:
  webnet:
    external: true
volumes:
  pgdata: